version: '3.8'

services:
  frontend:
    build: ./public
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - '5000:5000'
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
